### ISSUE TITLE
Php 7.0 is supported ?

### ISSUE THREAD

**Issue by JulienVandenberg** [poef/ripcord#12]
"It uses PHP's xmlrpc library and it needs at least PHP 5.". 

Should I understand 5 and more .. or 5.X only ?

**Comment by poef** [comment]
Well, I actually haven't updated or even used this in quite a while, so I don't know. There are a couple of forks that have more recent updates / changes, so if this one doesn't work, you could try those. One I found is at https://github.com/DarkaOnLine/Ripcord

**Comment by JulienVandenberg** [comment]
Thanks for your answer. 

I did it and it works.
